- name: Stop Apache
  systemd:
    name: apache2
    state: stopped
  when: ansible_os_family == "Debian"

- name: Remove Apache
  package:
    name: apache2
    state: absent
  when: ansible_os_family == "Debian"
