- name: Install Puppet via DPKG
  command: dpkg -i /tmp/puppet6-release-xenial.deb
#  when: ansible_os_family == "Debian"

- name: Install Puppet agent Ubuntu
  apt:
    name: puppet-agent
    state: present
